//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.SessionFilm = new HashSet<SessionFilm>();
            this.NetCinema = new HashSet<NetCinema>();
            this.CreatorCountry = new HashSet<CreatorCountry>();
            this.Genre = new HashSet<Genre>();
        }
    
        public int IdFilm { get; set; }
        public string MovieTitle { get; set; }
        public string Description { get; set; }
        public string Director { get; set; }
        public short DurationInMinute { get; set; }
        public System.DateTime PremierDate { get; set; }
        public byte IdAgeRestriction { get; set; }
        public decimal Rating { get; set; }
        public int IdMovieStudio { get; set; }
        public decimal MovieBudget { get; set; }
        public byte IdMovieDistributor { get; set; }
    
        public virtual AgeRestriction AgeRestriction { get; set; }
        public virtual MovieDistributor MovieDistributor { get; set; }
        public virtual MovieStudio MovieStudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionFilm> SessionFilm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NetCinema> NetCinema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreatorCountry> CreatorCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genre> Genre { get; set; }
    }
}
