//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCashReceipt
    {
        public int IdProduct { get; set; }
        public int IdCashReceipt { get; set; }
        public int Count { get; set; }
    
        public virtual CashReceipt CashReceipt { get; set; }
        public virtual Product Product { get; set; }
    }
}
