//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CashInfo
    {
        public int IdCashReceipt { get; set; }
        public string ФИО_клиента { get; set; }
        public string Контактная_информация { get; set; }
        public string Статус_дисконтной_карты { get; set; }
        public Nullable<int> Персональные_бонусы { get; set; }
        public string ФИО_работника { get; set; }
        public string Должность_работника { get; set; }
        public System.DateTime Дата_продажи { get; set; }
    }
}
