//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EmployeeInfo
    {
        public string ФИО_сотрудника { get; set; }
        public string Серия_и_номер_паспорта { get; set; }
        public string GenderTitle { get; set; }
        public System.DateTime Birthday { get; set; }
        public string PositionTitle { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Сколько_раз_сотрудник_оформлял_заказ { get; set; }
    }
}
