//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FilmInfo
    {
        public string Название_фильма { get; set; }
        public string Описание_фильма { get; set; }
        public string Режиссёр { get; set; }
        public string Продолжительность_фильма { get; set; }
        public System.DateTime Дата_премьеры { get; set; }
        public Nullable<byte> Возрастное_ограничение { get; set; }
        public decimal Рейтинг_фильма { get; set; }
        public string Название_киностудии { get; set; }
        public decimal Бюджет_фильма { get; set; }
        public string Страна { get; set; }
        public string Жанр { get; set; }
        public Nullable<int> Количество_билетов { get; set; }
    }
}
