//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MovieHallInfo
    {
        public string CinemaTitle { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string TypeHall { get; set; }
        public byte HallNumber { get; set; }
        public byte CountPlace { get; set; }
        public string ФИО_сотрудника_ответственного_за_кинозал { get; set; }
    }
}
