//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProductInfo
    {
        public string ProductTitle { get; set; }
        public decimal Cost { get; set; }
        public Nullable<byte> Count { get; set; }
        public string CategoryTitle { get; set; }
        public string Адрес_поставщика_ов_ { get; set; }
        public string ИНН_поставщика_ов_ { get; set; }
        public string Телефон_поставщика_ов_ { get; set; }
        public Nullable<int> Сколько_раз_покупали_продукт { get; set; }
    }
}
